Comment out get_ipython() call to get coordinate-frames.py running
The get_ipython() call before the matplotlib calls was required to
get the resulting plots to show up in the Jupyter Notebook, but it
causes this error when calling python coordinate-frames.py directly
in the command prompt:

    Traceback (most recent call last):
      File "coordinate-frames.py", line 318, in <module>
        get_ipython().run_line_magic('matplotlib', 'notebook')
    NameError: name 'get_ipython' is not defined

Commenting out this call avoids the error and correctly pops up
an interactive plot window at that point in the script.